### PR TITLE
Cleaning up Code Fommating

### PR DESCRIPTION
**Pull request by Wizard603**
Cleaned up code spacing and bracket spacing so it should be more uniform now

### CODE REVIEW

**Comment by Bensonwu02** [comment]
Looks good Kyle.

**Review by Bensonwu02 — APPROVED** [review]
Looks good kyle

**Review by cdsgibson — APPROVED** [review]
Everything looks a lot cleaner!!

**Review by tylerkj1209 — APPROVED** [review]
The modifications make sense. This looks good.

**Pull request merged**
