### PR TITLE
Feature goal tracking

### PR DESCRIPTION
**Pull request by Bensonwu02**
Implemented goal tracking feature
- makes use of decorator design pattern to extend metric summary functionality

Made changes to metric and metricstorage classes to allow goal tracking.

### CODE REVIEW

**Review by tylerkj1209 — DISMISSED** [review]
Thank you for changing the 7 day restriction on the metric summary use case. Now it may be possible for us to do a live demo of metric summary without having to import data.

**Review by Wizard603 — APPROVED** [review]
Changes required

**Review by cdsgibson — DISMISSED** [review]

**Review by dozysushi — APPROVED** [review]

**Comment by Bensonwu02** [comment]
Fixed changes requested by kyle. Delete some unused, duplicated classes in presenters package from caleb's recent pull request

**Review by dozysushi — APPROVED** [review]

**Review by Wizard603 — APPROVED** [review]
Changes look good

**Pull request merged**
