### PR TITLE
[Added Feature] Import data and export data

### PR DESCRIPTION
**Pull request by Wizard603**
Implemented import feature and export feature. Test pass locally, but I will need to make some changes to the auto grading on GitHub since they seem to be having some issues. Files can be imported and exported to and from .csv files. For examples on the csv format look in the ./test data/ folder. 

Also added equal methods in DataPoint and Metric to compare with other DataPoints and Metrics

### CODE REVIEW

**Review by Bensonwu02 — DISMISSED** [review]
I think the 'gateway' name can be a little confusing. Might be good to be consistent with the rest of our naming. Gateway corresponds to use case interactor so you could rename it to dataExporter and dataImporter.

I don't think you need response models since you are only returning a string. You can just directly pass in a string into your calls to outputboundary in the use case interactor classes.

**Review by cdsgibson — APPROVED** [review]

**Review by Bensonwu02 — APPROVED** [review]
Thanks for making the changes!

**Review by tylerkj1209 — APPROVED** [review]
Everything looks good. One thing that I already created a workaround for, but might be something we change in the future is the format you wrote for storing dates in DataPoint. Since it goes down to the resolution of seconds, I had to write extra code in order to check that specifically the day of the year was not the same. Perhaps in the future you could change the formatting so that it doesn't include hours minutes seconds since only 1 datapoint can be added per day per metric. Everything else seems like it works, though I recommend writing more tests just to ensure that all edge cases work. You know your code best, so try writing extra tests that you think might break your code, just to ensure that it breaks in a predictable way.

**Comment by Wizard603** [comment]
Test were fixed in HOTFIX branch

**Pull request merged**
